### ISSUE TITLE
how can I get *.pth files?

### ISSUE THREAD

**Issue by jixingwu** [wang-chen/AirCode#1]
Hello, I am a beginner. When I run `python experiments/place_recogination/online_relocalization.py -c config/experiment_tracking.yaml -g 1 -s results/ -d /media/jixingwu/datasetj/KITTI/Odom/data_odometry_color/sequences -m models/`, points_model.pth file is needed. So how can I get it?
Thank you!

**Comment by xukuanHIT** [comment]
Hi, models can be found [here](https://github.com/wang-chen/AirCode/releases/tag/v1.0.0).

**Comment by jixingwu** [comment]
Hi, thanks for your reply. But there is faster rcnn error occurred, like:
`Traceback (most recent call last):
  File "experiments/place_recogination/online_relocalization.py", line 150, in <module>
    main()
  File "experiments/place_recogination/online_relocalization.py", line 147, in main
    relocalization(configs)
  File "experiments/place_recogination/online_relocalization.py", line 46, in relocalization
    maskrcnn_model = build_maskrcnn(configs)
  File "./model/build_model.py", line 43, in build_maskrcnn
    model = MaskRCNN(backbone, nclass, image_mean=image_mean, image_std=image_std)
  File "./model/mask_rcnn/mask_rcnn.py", line 217, in __init__
    super(MaskRCNN, self).__init__(
  File "/home/jixingwu/anaconda3/lib/python3.8/site-packages/torchvision/models/detection/faster_rcnn.py", line 171, in __init__
    assert isinstance(box_roi_pool, (MultiScaleRoIAlign, type(None)))
AssertionError`
So, whether we need to perform pre-training or other operators before running that command?

**Comment by xukuanHIT** [comment]
No, you can run it directly.

This AssertionError is strange as "box_roi_pool" has been defined as an instance of "MultiScaleRoIAlign" [here](https://github.com/wang-chen/AirCode/blob/master/model/mask_rcnn/mask_rcnn.py#L204).

Could you check the type of "box_roi_pool" in your computer and tell me the version of your torchvision?

**Comment by jixingwu** [comment]
Yes, torch==1.8.1, torchversion==0.9.1. And I have checked that the type of "box_roi_pool" is "<class 'torchvision.ops.poolers.MultiScaleRoIAlign'>"

**Comment by xukuanHIT** [comment]
My torchvision version is 0.8.0, and I find the __init__ function of FasterRCNN has been changed in v0.9.0 and there are more parameters. You can compare [this line](https://github.com/pytorch/vision/blob/v0.9.0/torchvision/models/detection/faster_rcnn.py#L156) and [this line](https://github.com/pytorch/vision/blob/v0.8.0/torchvision/models/detection/faster_rcnn.py#L156).
