### ISSUE TITLE
Why RGB image is converted into grayscale image with 3 channels?

### ISSUE THREAD

**Issue by MarkChenYutian** [wang-chen/AirCode#3]
Hi, I'm trying to use AirCode to do object matching on complete KITTI sequences and I'm reading the code in `experiments/show_object_matching.py`. 

While reading the code, I noticed that the current code is reading RGB image sequence, convert it into grayscale image, and then duplicate the image into 3-channel each with same value (as following):

https://github.com/wang-chen/AirCode/blob/5e23e9f5322d2e4ee119d5326a6b6112cef0e6bd/experiments/show_object_matching/show_object_matching.py#L172-L176

I'm a bit unsure about the reason why this operation is performed here as the original RGB image should contain more information about the object comparing to grayscale image. For instance, it should be easier to distinguish objects with different color but similar shape if the RGB value is preserved.

**Comment by xukuanHIT** [comment]
@MarkChenYutian Hi, AirCode is originally intended to be used in visual SLAM, where grayscale images are often used.

**Comment by MarkChenYutian** [comment]
Thanks for reply! I've modified the `read_image` function so it read color image directly and seems that it works.
